# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Popot'Art
description: > # this means to ignore newlines until "baseurl:"
  Popot'art propose des histoires et des ateliers artistiques dans les institutions du secteur social et pédagogique (aide à la jeunesse, maisons d'accueil, crèches, écoles, etc.). Les animations sont présentées aux institutions en complément à leurs actions dans le but de développer du lien, stimuler l'éveil et renforcer l'estime de soi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
lang: fr


# Build settings
include: ['_pages']

collections:
  ateliers:
    output: true 
  sections:  
    
sass:
  sass_dir: _sass
  style: compressed
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

exclude: ["README.md", "LICENSE.md", "screenshot.png", "non utilises"]

# Google maps
google_maps_javascript_api_key: "AIzaSyC0P3hBe-WR5r_e0CYu1d2tXx30RwLR59M"
